import { Project, Package } from "../types";

export interface NotebookCell {
  cell_type: "markdown" | "code";
  metadata: Record<string, any>;
  source: string[];
}

export interface NotebookJSON {
  cells: NotebookCell[];
  metadata: {
    kernelspec: {
      display_name: string;
      language: string;
      name: string;
    };
    language_info: {
      codemirror_mode: {
        name: string;
        version: number;
      };
      file_extension: string;
      mimetype: string;
      name: string;
      nbconvert_exporter: string;
      pygments_lexer: string;
      version: string;
    };
  };
  nbformat: number;
  nbformat_minor: number;
}

function renderPipInstall(dependencies: Package[]): string[] {
  if (dependencies.length === 0) return [];
  const names = dependencies.map(d => d.name).join(" ");
  return [
    "# Install project dependencies\n",
    `!pip install -q ${names} huggingface_hub`
  ];
}

function renderHFLogin(): string[] {
  return [
    "# Hugging Face Authentication\n",
    "import os\n",
    "from huggingface_hub import login\n",
    "\n",
    "# Set HF_TOKEN in Colab Secrets (Left sidebar -> Key icon)\n",
    "token = os.environ.get('HF_TOKEN')\n",
    "if token:\n",
    "    login(token=token)\n",
    "else:\n",
    "    print('Warning: HF_TOKEN not found in environment.')\n",
    "    # login() # Fallback to manual login if needed"
  ];
}

function renderDataLoading(dataSources: any[]): string[] {
  if (dataSources.length === 0) return ["# No data sources defined"];
  
  const sources = dataSources.map(ds => {
    return `# Source: ${ds.name} (${ds.type})\n# Path: ${ds.path}\n`;
  }).join("\n");

  return [
    "# Data Loading Setup\n",
    sources
  ];
}

export function generateNotebook(project: Project, llmGeneratedCode: string): NotebookJSON {
  const cells: NotebookCell[] = [
    {
      cell_type: "markdown",
      metadata: {},
      source: [
        `# ${project.name}\n`,
        `${project.description}\n`,
        `\n--- \n`,
        `*Generated by ColabFlow*`
      ]
    },
    {
      cell_type: "code",
      metadata: {},
      source: renderPipInstall(project.dependencies)
    },
    {
      cell_type: "code",
      metadata: {},
      source: renderHFLogin()
    },
    {
      cell_type: "code",
      metadata: {},
      source: renderDataLoading(project.dataSources)
    },
    {
      cell_type: "markdown",
      metadata: {},
      source: ["## ML Logic & Model Initialization\n", "The following section is generated via AI suggestions."]
    },
    {
      cell_type: "code",
      metadata: {},
      source: llmGeneratedCode.split("\n").map(line => line + "\n")
    }
  ];

  return {
    cells,
    metadata: {
      kernelspec: {
        display_name: "Python 3",
        language: "python",
        name: "python3"
      },
      language_info: {
        codemirror_mode: {
          name: "ipython",
          version: 3
        },
        file_extension: ".py",
        mimetype: "text/x-python",
        name: "python",
        nbconvert_exporter: "python",
        pygments_lexer: "ipython3",
        version: "3.10.12"
      }
    },
    nbformat: 4,
    nbformat_minor: 5
  };
}

export function downloadNotebook(project: Project, llmGeneratedCode: string) {
  const nb = generateNotebook(project, llmGeneratedCode);
  const blob = new Blob([JSON.stringify(nb, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${project.name.replace(/\s+/g, '_').toLowerCase()}.ipynb`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadPythonScript(project: Project, llmGeneratedCode: string) {
  const scriptContent = [
    `# Project: ${project.name}`,
    `# Description: ${project.description}`,
    "",
    ...renderPipInstall(project.dependencies),
    "",
    ...renderHFLogin(),
    "",
    ...renderDataLoading(project.dataSources),
    "",
    "# ML Logic",
    llmGeneratedCode
  ].join("\n");

  const blob = new Blob([scriptContent], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${project.name.replace(/\s+/g, '_').toLowerCase()}.py`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
